sudo: false
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0
  - ruby-head

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gem install bundler

script:
  - bundle exec rake test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f2391f05f5fd4d55bf0
